// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Muno.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_categories_restaurant_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.Categories.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreId")
                        .HasColumnType("integer")
                        .HasColumnName("core_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_category_translation");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_category_translation_language_code");

                    b.HasIndex("CoreId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_category_translation_core_id_language_code");

                    b.ToTable("category_translation", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsRtl")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rtl");

                    b.HasKey("Code")
                        .HasName("pk_languages");

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "en-US",
                            DisplayName = "English",
                            IsRtl = false
                        },
                        new
                        {
                            Code = "fa-IR",
                            DisplayName = "فارسی",
                            IsRtl = true
                        });
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItemVariants.MenuItemVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_item_id");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.HasKey("Id")
                        .HasName("pk_menu_item_variant");

                    b.HasIndex("MenuItemId")
                        .HasDatabaseName("ix_menu_item_variant_menu_item_id");

                    b.ToTable("menu_item_variant", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItemVariants.MenuItemVariantTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreId")
                        .HasColumnType("integer")
                        .HasColumnName("core_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("detail");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_menu_item_variant_translation");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_menu_item_variant_translation_language_code");

                    b.HasIndex("CoreId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_menu_item_variant_translation_core_id_language_code");

                    b.ToTable("menu_item_variant_translation", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItems.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int?>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.HasKey("Id")
                        .HasName("pk_menu_items");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("ix_menu_items_section_id");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItems.MenuItemTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreId")
                        .HasColumnType("integer")
                        .HasColumnName("core_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_menu_item_translations");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_menu_item_translations_language_code");

                    b.HasIndex("CoreId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_menu_item_translations_core_id_language_code");

                    b.ToTable("menu_item_translations", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.Restaurants.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasColumnName("logo_path");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<Dictionary<string, string>>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("hstore")
                        .HasColumnName("opening_hours");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_restaurants_owner_id");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.Restaurants.RestaurantTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<int>("CoreId")
                        .HasColumnType("integer")
                        .HasColumnName("core_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_restaurant_translation");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_restaurant_translation_language_code");

                    b.HasIndex("CoreId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_restaurant_translation_core_id_language_code");

                    b.ToTable("restaurant_translation", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.Sections.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("Id")
                        .HasName("pk_sections");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_sections_category_id");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.Sections.SectionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreId")
                        .HasColumnType("integer")
                        .HasColumnName("core_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_section_translation");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("ix_section_translation_language_code");

                    b.HasIndex("CoreId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_section_translation_core_id_language_code");

                    b.ToTable("section_translation", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Muno.Domain.Entities.Categories.Category", b =>
                {
                    b.HasOne("Muno.Domain.Entities.Restaurants.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_restaurants_restaurant_id");

                    b.OwnsOne("Muno.Domain.Entities.ActivityPeriod", "ActivityPeriod", b1 =>
                        {
                            b1.Property<int>("CategoryId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("ActivityType")
                                .HasColumnType("integer")
                                .HasColumnName("activity_type");

                            b1.Property<TimeSpan>("FromTime")
                                .HasColumnType("interval")
                                .HasColumnName("from_time");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<TimeSpan>("ToTime")
                                .HasColumnType("interval")
                                .HasColumnName("to_time");

                            b1.HasKey("CategoryId");

                            b1.ToTable("categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_categories_categories_id");
                        });

                    b.Navigation("ActivityPeriod")
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Categories.CategoryTranslation", b =>
                {
                    b.HasOne("Muno.Domain.Entities.Categories.Category", "Core")
                        .WithMany("Translations")
                        .HasForeignKey("CoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_translation_categories_core_id");

                    b.HasOne("Muno.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_translation_languages_language_code");

                    b.Navigation("Core");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItemVariants.MenuItemVariant", b =>
                {
                    b.HasOne("Muno.Domain.Entities.MenuItems.MenuItem", "MenuItem")
                        .WithMany("Variants")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_variant_menu_items_menu_item_id");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItemVariants.MenuItemVariantTranslation", b =>
                {
                    b.HasOne("Muno.Domain.Entities.MenuItemVariants.MenuItemVariant", "Core")
                        .WithMany("Translations")
                        .HasForeignKey("CoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_variant_translation_menu_item_variant_core_id");

                    b.HasOne("Muno.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_variant_translation_languages_language_code");

                    b.Navigation("Core");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItems.MenuItem", b =>
                {
                    b.HasOne("Muno.Domain.Entities.Sections.Section", "Section")
                        .WithMany("MenuItems")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_menu_items_sections_section_id");

                    b.OwnsOne("Muno.Domain.Entities.ActivityPeriod", "ActivityPeriod", b1 =>
                        {
                            b1.Property<int>("MenuItemId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("ActivityType")
                                .HasColumnType("integer")
                                .HasColumnName("activity_type");

                            b1.Property<TimeSpan>("FromTime")
                                .HasColumnType("interval")
                                .HasColumnName("from_time");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<TimeSpan>("ToTime")
                                .HasColumnType("interval")
                                .HasColumnName("to_time");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("menu_items");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId")
                                .HasConstraintName("fk_menu_items_menu_items_id");
                        });

                    b.Navigation("ActivityPeriod")
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItems.MenuItemTranslation", b =>
                {
                    b.HasOne("Muno.Domain.Entities.MenuItems.MenuItem", "Core")
                        .WithMany("Translations")
                        .HasForeignKey("CoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_translations_menu_items_core_id");

                    b.HasOne("Muno.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_menu_item_translations_languages_language_code");

                    b.Navigation("Core");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Restaurants.Restaurant", b =>
                {
                    b.HasOne("Muno.Domain.Entities.User", "Owner")
                        .WithMany("Restaurants")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurants_users_owner_id");

                    b.OwnsOne("Muno.Domain.Entities.ActivityPeriod", "ActivityPeriod", b1 =>
                        {
                            b1.Property<int>("RestaurantId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("ActivityType")
                                .HasColumnType("integer")
                                .HasColumnName("activity_type");

                            b1.Property<TimeSpan>("FromTime")
                                .HasColumnType("interval")
                                .HasColumnName("from_time");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<TimeSpan>("ToTime")
                                .HasColumnType("interval")
                                .HasColumnName("to_time");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_id");
                        });

                    b.Navigation("ActivityPeriod")
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Restaurants.RestaurantTranslation", b =>
                {
                    b.HasOne("Muno.Domain.Entities.Restaurants.Restaurant", "Core")
                        .WithMany("Translations")
                        .HasForeignKey("CoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_translation_restaurants_core_id");

                    b.HasOne("Muno.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_translation_languages_language_code");

                    b.Navigation("Core");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Sections.Section", b =>
                {
                    b.HasOne("Muno.Domain.Entities.Categories.Category", "Category")
                        .WithMany("Sections")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_sections_categories_category_id");

                    b.OwnsOne("Muno.Domain.Entities.ActivityPeriod", "ActivityPeriod", b1 =>
                        {
                            b1.Property<int>("SectionId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("ActivityType")
                                .HasColumnType("integer")
                                .HasColumnName("activity_type");

                            b1.Property<TimeSpan>("FromTime")
                                .HasColumnType("interval")
                                .HasColumnName("from_time");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<TimeSpan>("ToTime")
                                .HasColumnType("interval")
                                .HasColumnName("to_time");

                            b1.HasKey("SectionId");

                            b1.ToTable("sections");

                            b1.WithOwner()
                                .HasForeignKey("SectionId")
                                .HasConstraintName("fk_sections_sections_id");
                        });

                    b.Navigation("ActivityPeriod")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Sections.SectionTranslation", b =>
                {
                    b.HasOne("Muno.Domain.Entities.Sections.Section", "Core")
                        .WithMany("Translations")
                        .HasForeignKey("CoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_section_translation_sections_core_id");

                    b.HasOne("Muno.Domain.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_section_translation_languages_language_code");

                    b.Navigation("Core");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Muno.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Muno.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Muno.Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Categories.Category", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItemVariants.MenuItemVariant", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Muno.Domain.Entities.MenuItems.MenuItem", b =>
                {
                    b.Navigation("Translations");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Restaurants.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Muno.Domain.Entities.Sections.Section", b =>
                {
                    b.Navigation("MenuItems");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Muno.Domain.Entities.User", b =>
                {
                    b.Navigation("Restaurants");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
